sudo:false
# safelist
branches:
  only:
   - gh-pages

before_script:
   - gem install travis
script:
   - chmod +x trigger.sh
   - chmod +x get-build-status.sh
   - ./trigger.sh binary-com binary-static-ci gh-pages $TRAVIS_ACCESS_TOKEN
   - sleep 60 #wait for the dependent build to start
   - ./get-build-status.sh binary-com binary-static-ci $TRAVIS_ACCESS_TOKEN